// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiqo.Infrastructure.Persistence;

#nullable disable

namespace Profiqo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProfiqoDbContext))]
    [Migration("20260126010515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiqo.Domain.Automation.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_automation_rules");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_automation_rules_tenant_id_status");

                    b.ToTable("automation_rules", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TenantId", "LastSeenAtUtc")
                        .HasDatabaseName("ix_customers_tenant_id_last_seen_at_utc");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Integrations.ProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account_id");

                    b.Property<short>("ProviderType")
                        .HasColumnType("smallint")
                        .HasColumnName("provider_type");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_provider_connections");

                    b.HasIndex("TenantId", "ProviderType")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_connections_tenant_id_provider_type");

                    b.ToTable("provider_connections", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Messaging.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_message_templates");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_message_templates_tenant_id_name");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CostBreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cost_breakdown_json");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at_utc");

                    b.Property<string>("ProviderOrderId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_order_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("TenantId", "Channel", "ProviderOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_tenant_id_channel_provider_order_id");

                    b.HasIndex("TenantId", "CustomerId", "PlacedAtUtc")
                        .HasDatabaseName("ix_orders_tenant_id_customer_id_placed_at_utc");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles_json")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Profiqo.Infrastructure.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("TenantId", "ConsumerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_tenant_id_consumer_name_message_id");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Profiqo.Infrastructure.Persistence.Entities.IngestionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<short>("ProcessingStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("provider_event_id");

                    b.Property<short>("ProviderType")
                        .HasColumnType("smallint")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_valid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_events");

                    b.HasIndex("ProcessingStatus", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_ingestion_events_processing_status_next_attempt_at_utc");

                    b.HasIndex("TenantId", "ProviderType", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_ingestion_events_tenant_id_provider_type_provider_event_id");

                    b.ToTable("ingestion_events", (string)null);
                });

            modelBuilder.Entity("Profiqo.Infrastructure.Persistence.Entities.IntegrationCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CursorKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cursor_key");

                    b.Property<string>("CursorValue")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("cursor_value");

                    b.Property<Guid>("ProviderConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_connection_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_integration_cursors");

                    b.HasIndex("TenantId", "ProviderConnectionId", "CursorKey")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_cursors_tenant_id_provider_connection_id_cursor");

                    b.ToTable("integration_cursors", (string)null);
                });

            modelBuilder.Entity("Profiqo.Infrastructure.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt_at_utc");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_occurred_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Profiqo.Domain.Automation.AutomationRule", b =>
                {
                    b.OwnsOne("Profiqo.Domain.Automation.DelayDefinition", "Delay", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<short>("Unit")
                                .HasColumnType("smallint")
                                .HasColumnName("delay_unit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("delay_value");

                            b1.HasKey("AutomationRuleId");

                            b1.ToTable("automation_rules");

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rules_automation_rules_id");
                        });

                    b.OwnsOne("Profiqo.Domain.Automation.GoalDefinition", "Goal", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("AttributionWindowDays")
                                .HasColumnType("integer")
                                .HasColumnName("goal_window_days");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("goal_type");

                            b1.HasKey("AutomationRuleId");

                            b1.ToTable("automation_rules");

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rules_automation_rules_id");
                        });

                    b.OwnsMany("Profiqo.Domain.Automation.RuleAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("automation_rule_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<short?>("Channel")
                                .HasColumnType("smallint")
                                .HasColumnName("channel");

                            b1.Property<string>("PersonalizationJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("personalization_json");

                            b1.Property<string>("SegmentId")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("segment_id");

                            b1.Property<string>("Tag")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("tag");

                            b1.Property<string>("TaskAssignee")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("task_assignee");

                            b1.Property<string>("TaskDescription")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("task_description");

                            b1.Property<Guid?>("TemplateId")
                                .HasColumnType("uuid")
                                .HasColumnName("template_id");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("type");

                            b1.HasKey("AutomationRuleId", "Id")
                                .HasName("pk_automation_rule_actions");

                            b1.HasIndex("AutomationRuleId")
                                .HasDatabaseName("ix_automation_rule_actions_automation_rule_id");

                            b1.ToTable("automation_rule_actions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rule_actions_automation_rules_automation_rule_id");
                        });

                    b.OwnsMany("Profiqo.Domain.Automation.RuleCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("automation_rule_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("field");

                            b1.Property<short>("Operator")
                                .HasColumnType("smallint")
                                .HasColumnName("op");

                            b1.Property<string>("ValueJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("value_json");

                            b1.HasKey("AutomationRuleId", "Id")
                                .HasName("pk_automation_rule_conditions");

                            b1.HasIndex("AutomationRuleId")
                                .HasDatabaseName("ix_automation_rule_conditions_automation_rule_id");

                            b1.ToTable("automation_rule_conditions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rule_conditions_automation_rules_automation_rule");
                        });

                    b.OwnsOne("Profiqo.Domain.Automation.RuleLimits", "Limits", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CooldownHours")
                                .HasColumnType("integer")
                                .HasColumnName("limit_cooldown_hours");

                            b1.Property<int>("MaxPerCustomerPerDay")
                                .HasColumnType("integer")
                                .HasColumnName("limit_max_per_day");

                            b1.Property<int>("MaxPerCustomerTotal")
                                .HasColumnType("integer")
                                .HasColumnName("limit_max_total");

                            b1.HasKey("AutomationRuleId");

                            b1.ToTable("automation_rules");

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rules_automation_rules_id");
                        });

                    b.OwnsOne("Profiqo.Domain.Automation.TriggerDefinition", "Trigger", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CronExpression")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("trigger_cron");

                            b1.Property<string>("EventType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("trigger_event_type");

                            b1.Property<string>("ScoreField")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("trigger_score_field");

                            b1.Property<short?>("ScoreOperator")
                                .HasColumnType("smallint")
                                .HasColumnName("trigger_score_operator");

                            b1.Property<string>("ScoreValueJson")
                                .HasColumnType("jsonb")
                                .HasColumnName("trigger_score_value_json");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("trigger_type");

                            b1.HasKey("AutomationRuleId");

                            b1.ToTable("automation_rules");

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId")
                                .HasConstraintName("fk_automation_rules_automation_rules_id");
                        });

                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("Delay")
                        .IsRequired();

                    b.Navigation("Goal")
                        .IsRequired();

                    b.Navigation("Limits")
                        .IsRequired();

                    b.Navigation("Trigger")
                        .IsRequired();
                });

            modelBuilder.Entity("Profiqo.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("Profiqo.Domain.Customers.CustomerAiScores", "AiScores", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ChurnRiskScore")
                                .HasColumnType("integer")
                                .HasColumnName("ai_churn_risk");

                            b1.Property<DateTimeOffset>("ComputedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ai_computed_at_utc");

                            b1.Property<int>("DiscountSensitivityScore")
                                .HasColumnType("integer")
                                .HasColumnName("ai_discount_sensitivity");

                            b1.Property<decimal>("Ltv12mProfit")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("ai_ltv_12m_profit");

                            b1.Property<DateTimeOffset?>("NextPurchaseAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ai_next_purchase_at_utc");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_id");
                        });

                    b.OwnsMany("Profiqo.Domain.Customers.CustomerConsent", "Consents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at_utc");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("ip_address");

                            b1.Property<string>("PolicyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("policy_version");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("source");

                            b1.Property<short>("Status")
                                .HasColumnType("smallint")
                                .HasColumnName("status");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("type");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("user_agent");

                            b1.HasKey("Id")
                                .HasName("pk_customer_consents");

                            b1.HasIndex("CustomerId", "Status")
                                .HasDatabaseName("ix_customer_consents_customer_id_status");

                            b1.HasIndex("CustomerId", "Type")
                                .IsUnique()
                                .HasDatabaseName("ix_customer_consents_customer_id_type");

                            b1.ToTable("customer_consents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customer_consents_customers_customer_id");
                        });

                    b.OwnsMany("Profiqo.Domain.Customers.CustomerIdentity", "Identities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<DateTimeOffset>("FirstSeenAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("first_seen_at_utc");

                            b1.Property<DateTimeOffset>("LastSeenAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_seen_at_utc");

                            b1.Property<string>("SourceExternalId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("source_external_id");

                            b1.Property<short?>("SourceProvider")
                                .HasColumnType("smallint")
                                .HasColumnName("source_provider");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("type");

                            b1.Property<string>("ValueHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("value_hash");

                            b1.HasKey("Id")
                                .HasName("pk_customer_identities");

                            b1.HasIndex("CustomerId")
                                .HasDatabaseName("ix_customer_identities_customer_id");

                            b1.HasIndex("TenantId", "Type", "ValueHash")
                                .IsUnique()
                                .HasDatabaseName("ix_customer_identities_tenant_id_type_value_hash");

                            b1.ToTable("customer_identities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customer_identities_customers_customer_id");

                            b1.OwnsOne("Profiqo.Domain.Common.Types.EncryptedSecret", "ValueEncrypted", b2 =>
                                {
                                    b2.Property<Guid>("CustomerIdentityId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Algorithm")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("value_algorithm");

                                    b2.Property<string>("CipherText")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("value_ciphertext");

                                    b2.Property<string>("KeyId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("value_key_id");

                                    b2.HasKey("CustomerIdentityId");

                                    b2.ToTable("customer_identities");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerIdentityId")
                                        .HasConstraintName("fk_customer_identities_customer_identities_id");
                                });

                            b1.Navigation("ValueEncrypted");
                        });

                    b.OwnsOne("Profiqo.Domain.Customers.CustomerRfm", "Rfm", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ComputedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("rfm_computed_at_utc");

                            b1.Property<int>("FrequencyScore")
                                .HasColumnType("integer")
                                .HasColumnName("rfm_f");

                            b1.Property<int>("MonetaryScore")
                                .HasColumnType("integer")
                                .HasColumnName("rfm_m");

                            b1.Property<int>("RecencyScore")
                                .HasColumnType("integer")
                                .HasColumnName("rfm_r");

                            b1.Property<short>("Segment")
                                .HasColumnType("smallint")
                                .HasColumnName("rfm_segment");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_id");
                        });

                    b.Navigation("AiScores");

                    b.Navigation("Consents");

                    b.Navigation("Identities");

                    b.Navigation("Rfm");
                });

            modelBuilder.Entity("Profiqo.Domain.Integrations.ProviderConnection", b =>
                {
                    b.OwnsOne("Profiqo.Domain.Common.Types.EncryptedSecret", "AccessToken", b1 =>
                        {
                            b1.Property<Guid>("ProviderConnectionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("access_token_algorithm");

                            b1.Property<string>("CipherText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("access_token_ciphertext");

                            b1.Property<string>("KeyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("access_token_key_id");

                            b1.HasKey("ProviderConnectionId");

                            b1.ToTable("provider_connections");

                            b1.WithOwner()
                                .HasForeignKey("ProviderConnectionId")
                                .HasConstraintName("fk_provider_connections_provider_connections_id");
                        });

                    b.OwnsOne("Profiqo.Domain.Common.Types.EncryptedSecret", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("ProviderConnectionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("refresh_token_algorithm");

                            b1.Property<string>("CipherText")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("refresh_token_ciphertext");

                            b1.Property<string>("KeyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("refresh_token_key_id");

                            b1.HasKey("ProviderConnectionId");

                            b1.ToTable("provider_connections");

                            b1.WithOwner()
                                .HasForeignKey("ProviderConnectionId")
                                .HasConstraintName("fk_provider_connections_provider_connections_id");
                        });

                    b.Navigation("AccessToken")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Profiqo.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("Profiqo.Domain.Common.Types.Money", "NetProfit", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("net_profit");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("net_profit_currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsOne("Profiqo.Domain.Common.Types.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsMany("Profiqo.Domain.Orders.OrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<int>("LineId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("line_id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("LineId"));

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("product_name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("sku");

                            b1.HasKey("OrderId", "LineId")
                                .HasName("pk_order_lines");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("ix_order_lines_order_id");

                            b1.ToTable("order_lines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_lines_orders_order_id");

                            b1.OwnsOne("Profiqo.Domain.Common.Types.Money", "LineTotal", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("order_id");

                                    b2.Property<int>("OrderLineLineId")
                                        .HasColumnType("integer")
                                        .HasColumnName("line_id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(19,4)")
                                        .HasColumnName("line_total");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("line_total_currency");

                                    b2.HasKey("OrderLineOrderId", "OrderLineLineId");

                                    b2.ToTable("order_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineLineId")
                                        .HasConstraintName("fk_order_lines_order_lines_order_id_line_id");
                                });

                            b1.OwnsOne("Profiqo.Domain.Common.Types.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("order_id");

                                    b2.Property<int>("OrderLineLineId")
                                        .HasColumnType("integer")
                                        .HasColumnName("line_id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(19,4)")
                                        .HasColumnName("unit_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_currency");

                                    b2.HasKey("OrderLineOrderId", "OrderLineLineId");

                                    b2.ToTable("order_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLineLineId")
                                        .HasConstraintName("fk_order_lines_order_lines_order_id_line_id");
                                });

                            b1.Navigation("LineTotal")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Lines");

                    b.Navigation("NetProfit")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
